<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PcBeaconAgent.Contracts</AssemblyName>
    <RootNamespace>PcBeaconAgent.Contracts</RootNamespace>
    <NoWarn>$(NoWarn);IL2026</NoWarn>
  </PropertyGroup>

</Project>