<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>

    <AssemblyName>PcBeaconAgent.Service</AssemblyName>
    <RootNamespace>PcBeaconAgent.Service</RootNamespace>
    <UserSecretsId>dotnet-PcBeaconAgent-cfec9708-b427-4f85-9e98-3cf8c1748e58</UserSecretsId>
    <NoWarn>$(NoWarn);NU1701</NoWarn>

    <ApplicationIcon>beacon.ico</ApplicationIcon>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfContained>true</IncludeNativeLibrariesForSelfContained>

    <Version Condition="'$(AppVersionName)' == ''">1.0.0</Version>
    <Version Condition="'$(AppVersionName)' != ''">$(AppVersionName)</Version>

    <AssemblyVersion Condition="'$(AppVersionName)' == ''">1.0.0.0</AssemblyVersion>
    <AssemblyVersion Condition="'$(AppVersionName)' != ''">$(AppVersionName).0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AudioSwitcher.AudioApi.CoreAudio" Version="3.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.9" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PcBeaconAgent.Client.Core\PcBeaconAgent.Client.Core.csproj" />
  </ItemGroup>
</Project>